# Generated by Django 2.1.1 on 2019-06-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_micropost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='micropost',
            name='content',
            field=models.TextField(max_length=140),
        ),
    ]
