# Generated by Django 2.1.1 on 2019-06-20 13:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_auto_20190620_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='micropost',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 20, 13, 27, 6, 714962, tzinfo=utc)),
        ),
    ]
